const menuItems = [
  {routerName: 'Button', label: 'Button'},
  {routerName: 'Checkbox', label: 'Checkbox'},
  {routerName: 'Chip', label: 'Chip'},
  {routerName: 'ColorSystem', label: 'Color System'},
  {routerName: 'Columns', label: 'Columns'},
  {routerName: 'Confirm', label: 'Confirm'},
  {routerName: 'DataTable', label: 'Data Table'},
  {routerName: 'DataTablePagination', label: 'Pagination'},
  {routerName: 'StatusList', label: 'Data Table Status'},
  {routerName: 'Delete', label: 'Delete'},
  {routerName: 'Dropdown', label: 'Dropdown'},
  {routerName: 'TestFileUploader', label: 'File Uploader'},
  {routerName: 'Modal', label: 'Modal'},
  {routerName: 'Notifications', label: 'Notifications'},
  {routerName: 'Radio', label: 'Radio'},
  {routerName: 'RadioButton', label: 'Radio Button'},
  {routerName: 'SideNavigation', label: 'Side Navigation'},
  {routerName: 'Spinner', label: 'Spinner'},
  {routerName: 'StarRating', label: 'Star Rating'},
  {routerName: 'Switch', label: 'Switch'},
  {routerName: 'Tabs', label: 'Tabs'},
  {routerName: 'Toggles', label: 'Toggles'},
  {routerName: 'TextField', label: 'Text Field'},
  {routerName: 'SelectField', label: 'Select Field'},
  // {routerName: 'MediaUploader', label: 'Media Uploader', stability: 'alpha'},
  // {routerName: 'MonthNavigation', label: 'Month Navigation', stability: 'alpha'},
  // {routerName: 'SignatureCanvas', label: 'Signature Canvas', stability: 'alpha'},
];

export default menuItems;
